version: '3.8'

services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind9/named.conf:/etc/bind/named.conf
      - ./bind9/zones:/etc/bind/zones
