version: '3.1'
services:
  teamspeak:
    image: teamspeaksystems/teamspeak6-server:latest
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 30033:30033
    environment:
      TSSERVER_LICENSE_ACCEPTED: accept
    volumes:
      - teamspeak-data:/var/tsserver/

volumes:
  teamspeak-data:
    name: teamspeak-data
